#
# Run `conda build .` to build this package
#

package:
  name: "lsst-mariadbclient"
  version: "0.10.1.11.3"

source:
  git_rev: "a3cbbea09f2ba4d2a6064595ba8d300c478cab0f"
  git_url: "https://github.com/LSST/mariadbclient"


build:
  number: 1
  string: "1"
#  binary_relocation: false

requirements:
  build:
    - eups >=2.0.2
    - gcc ==4.8.5                   # [not osx]
    - nomkl                         #
    - openssl
    - patchelf ==0.8                # [not osx]

  run:
    - eups >=2.0.2
    - libgcc >=4.8.5                # [not osx]
    - nomkl                         #
    - openssl

about:
  home: "https://github.com/LSST/mariadbclient"
#  license: GPLv2
#  summary: A version manager tracking product dependencies
