#
# Run `conda build .` to build this package
#

package:
  name: "lsst-ndarray"
  version: "1.3.0"

source:
  git_rev: "90f134a1b6d5b528ae64c106ffd1df14d6445ff6"
  git_url: "https://github.com/lsst/ndarray"
  patches:
        - 000-patch-eups-to-remove-fft-test.patch

build:
  number: 0
  string: "0"
#  binary_relocation: false

requirements:
  build:
    - eups >=2.0.2
    - lsst-boost ==1.60.1.post1
    - lsst-eigen ==3.2.5.2
    - lsst-fftw ==3.3.4.2
    - lsst-numpy-eups-configs ==0.0.3.post1
    - lsst-python-eups-configs ==0.0.6
    - lsst-swig-eups-configs ==3.0.10
    - nomkl                         #
    - numpy 1.10.4
    - python 2.7.*
    - swig ==3.0.10

  run:
    - eups >=2.0.2
    - libgcc >=4.8.5                # [not osx]
    - lsst-boost ==1.60.1.post1
    - lsst-eigen ==3.2.5.2
    - lsst-fftw ==3.3.4.2
    - lsst-numpy-eups-configs ==0.0.3.post1
    - lsst-python-eups-configs ==0.0.6
    - lsst-swig-eups-configs ==3.0.10
    - nomkl                         #

about:
  home: "https://github.com/LSST/ndarray"
#  license: GPLv2
#  summary: A version manager tracking product dependencies
