#
# Run `conda build .` to build this package
#

package:
  name: "lsst-wcslib"
  version: "5.13.1"

source:
  git_rev: "373bd44add489cc091272d3393ae8d9857bcd34d"
  git_url: "https://github.com/LSST/wcslib"
  patches:
        - 000_use_gcc_std_gnu89.patch

build:
  number: 0
  string: "0"
#  binary_relocation: false

requirements:
  build:
    - eups >=2.0.2
    - gcc ==4.8.5                   # [not osx]
    - lsst-cfitsio ==3360.4
    - nomkl                         #
    - patchelf ==0.8                # [not osx]

  run:
    - eups >=2.0.2
    - libgcc >=4.8.5                # [not osx]
    - lsst-cfitsio ==3360.4
    - nomkl                         #

about:
  home: "https://github.com/LSST/wcslib"
#  license: GPLv2
#  summary: A version manager tracking product dependencies
